// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { rememberMeStorage } from './rememberMeStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // rememberMeStorage wraps the existing storage so "Remember me" chooses
    // between persistent storage and a session-only store at login time.
    storage: rememberMeStorage(brokeredPreviewStorage() ?? localStorage),
    persistSession: true,
    autoRefreshToken: true,
  }
});